In [2]:
import pandas as pd 
import numpy as np

CSV CANAIS DE VENDA

(p)coluna canal de venda tem 'ota' o que seria?
(t)coluna comissão pct esta em str


CSV CLIENTE

(t) clientes duplicados (3?)
(p) temos clientes com todas as informações idênticas salvo coluna de estado de origem 

(t) coluna de tipo de cliente precisa ser padroni.
(p) NaN existente, não deveria constar como nulo?
(t) coluna estado de origem tem que ser padroni.
(p) coluna faixa_etaria com muito NaN PERGUNTA DE NEGOCIO, É IMPORTANTE PARA A LEITURA DO NEGOCIO


CSV FUNCIONARIO

(t) Coluna salatio str
(p) coluna salario 6 NaN IMPORTANTE PARA A LEITURA?
(t) leta maiuscula na coluna cargo


CSV RESERVAS

(t) Coluna status reserva precisa ser padronizado
(t) NaN na coluna id_canal e avaliação_ cliente IMPORTANTE PARA LEITURA
(t) Coluna forma de pagamento precisa padronizar

CSV tipos quarto

(t) coluna valor diaria base como str


CSV UNIDADES

(t) regiao precisa padronizar espaço no serra
(t) categoria hotel padronizar, nome ext. str
(t) padronizar nome das regiões, csv conta com: Capital, Serra, capital, CAP,Baixada Fluminense, Baixada fluminense,Serra           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [3]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('clientes.csv', sep=';')
pd.read_csv ('funcionarios.csv', sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'canais_venda.csv'

In [5]:
print('arquivo editado robert')

arquivo editado robert

In [31]:
df = pd.read_csv('unidades.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

id_unidade             int64
nome_unidade             str
cidade                   str
regiao                   str
categoria_hotel          str
num_quartos_total    float64
dtype: object

In [34]:
df['categoria_hotel'].value_counts()

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

In [ ]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)]

In [36]:
df[df.isnull().any(axis=1)]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN

In [37]:
df['categoria_hotel'].value_counts()

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

In [39]:
mapa = {
    '4 estrelas':                '4',
    '4 Estrelas':                '4',
    '3*':                        '3',
    'Três Estrelas':             '3',
    '3 estrelas':               '3',
    '5 estrelas':                '5',
    'cinco estrelas':            '5'
}
df['categoria_hotel'] = df['categoria_hotel'].map(mapa).fillna(df['categoria_hotel'])

print('Após mapeamento:')
print(sorted(df['categoria_hotel'].unique()))

Após mapeamento:
['3', '4', '5']

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [40]:
df['categoria_hotel'].value_counts()

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [ ]:
df

In [42]:
df['regiao'].value_counts()

regiao
Costa Verde           3
Capital               2
Serra                 2
capital               1
CAP                   1
Baixada Fluminense    1
Baixada fluminense    1
Serra                 1
Name: count, dtype: int64

In [43]:
reg = {
    'capital':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['regiao'] = df['regiao'].map(reg).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

Após mapeamento:
['Baixada Fluminense', 'Capital', 'Costa Verde', 'Serra', 'Serra ']

In [45]:
df['regiao'] = df['regiao'].str.strip().str.title()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [ ]:
df['num_quartos_total'] = df['num_quartos_total'].astype("Int64")
df

In [50]:
df = df.rename(columns={'categoria_hotel': 'categoria_hotel(estrelas)'})
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [52]:
df['categoria_hotel(estrelas)'] = pd.to_numeric(df['categoria_hotel(estrelas)'], errors="coerce").astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [57]:
df.to_csv('unidades.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50



CSV UNIDADES

(t) padronizado categoria hotel, deixados apenas números, 
(t) padronizado nome das regiões: Capital, Serra, Baixada Fluminense, Costa Verde           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [ ]:
df_tipo = pd.read_csv('tipos_quarto.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(6, 4)

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      STANDARD               2         R$ 280,00
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

id_tipo_quarto       int64
descricao              str
capacidade_max       int64
valor_diaria_base      str
dtype: object

In [58]:
df_tipo['descricao'] = df_tipo['descricao'].str.strip().str.title()
df_tipo

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      Standard               2         R$ 280,00
1               2      Superior               2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

In [ ]:
df_tipo['valor_diaria_base'] = (
df_tipo['valor_diaria_base']
.str.replace('R$', '', regex=False)
.str.replace(' ', '', regex=False)
.str.replace('.', '', regex=False) # remove separador de milhar
.str.replace(',', '.', regex=False)
.astype(float)
)

In [84]:
df_tipo.to_csv('tipos_quarto.csv', sep=';', index=False)

In [85]:
df_tipo

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

padronizado a escrita da couna 'descrição'
coluna 'valor_diaria_base'